#!/bin/bash

# Environment variable inputs:
#   TWITTER_CONSUMER
#   TWITTER_SECRET

# cd to app root
CWD=$(dirname $0)
if [[ `basename $(pwd)` = 'scripts' ]]; then
  cd ../
else
  cd `dirname $CWD`
fi


QUIET=
while getopts ":q" opt;do
  case $opt in
  q)
    QUIET="true"
    ;;
  \?)
    echoerr "Invalid arguemnts"
    print_help
    exit 1
    ;;
  :)
    echoerr "Option -${OPTARG} requires an argument."
    print_help
    exit 1
    ;;
  esac
done

shift $(($OPTIND - 1))
USERNAME=$1
FILE=$2

if [ -z "${TWITTER_CONSUMER}" ]; then
  echo "Must supply TWITTER_CONSUMER"
  if [[ -z "$QUIET" ]]; then
    exit 1
  else
    exit 0
  fi
fi

if [ -z "${TWITTER_SECRET}" ]; then
  echo "Must supply TWITTER_SECRET"
  if [[ -z "$QUIET" ]]; then
    exit 1
  else
    exit 0
  fi
fi

if [ -z "${USERNAME}" ] || [ -z "${FILE}" ]; then
  echo "Usage: $0 twitter_username output_path"
  if [[ -z "$QUIET" ]]; then
    exit 1
  else
    exit 0
  fi
fi

TOKEN_JSON=$(curl -s -u $TWITTER_CONSUMER:$TWITTER_SECRET -d 'grant_type=client_credentials' https://api.twitter.com/oauth2/token)
TOKEN=$(echo $TOKEN_JSON | jq -r .access_token)

curl -s -H "Authorization: Bearer $TOKEN" "https://api.twitter.com/1.1/favorites/list.json?count=12&screen_name=${USERNAME}" | jq . > $FILE
